### ISSUE TITLE
Dashboard not showing up in Grafana

### ISSUE THREAD

**Issue by preese** [doebi/speedtest#1]
I've seen this issue on a few packages, so it might be something in my environment.  I've tried it in a KVM on Fedora 36 and on a plain Fedora 36 on bare metal, same behavior with both.  Grafana is v 9.0.3, Influx is v 1.8.3. .  When I follow the readme and startup docker-compose, the expected things come to the screen yet when I look at the Grafana page, there isn't any dashboard available.  I'm very new to docker so I don't have a clue for how to start troubleshooting the issue.  Ideas?  Thanks.

**Comment by doebi** [comment]
Hi Phil, thanks for your inquiry.

If you are able to access grafana, your docker setup is working fine. To
view the dashboard as seen on the screenshot one additional step is
necessary. (which I should have mentioned in the readme)

Click on „Import“ under the Dashboards icon in the sidemenu and upload the
„dashboard.json“ found in the repo.

All the best,
doebi

**Comment by preese** [comment]
Hi Doebi,

Thanks very much for your prompt and very helpful response AND I got it going!

I'm sure these are nubie bits that I needed to work through to get your tool working.  Yes, I had to load up the dashboard.json file.  Then I needed to add the influx data source.  But the real issue was I needed to disable selinux on the host I ran the docker-compose from!  All of these make perfect sense, after the fact.

I really appreciate how streamlined you solution is for this 'speedtest' project.  It helps me better understand how all the container bits fit together.

Phil

**Comment by doebi** [comment]
Glad you got it working.

Automating the data source and dashboard into docker is still an open task
I am having for this project, but its rather sophisticated compared to the
manual setup.

The selinux issue is more low level and not directly in the scope of this
project or even docker, but you made it. No worries we are all learning
from each other, that’s how we survive in this business. :)

All the best,
doebi

**Comment by doebi** [comment]
I figured that provisioning dashboards and datasources for grafana in docker is way more easier than I expected and recently added it to the docker compose configuration. So I am closing this issue. :)
