### ISSUE TITLE
No Speedtest-Results

### ISSUE THREAD

**Issue by Gitarist2018** [doebi/speedtest#2]
Great project. Exactly what I was looking for, especially the PING display.

However, no speedtest results are displayed. When I run the speedtest.sh script manually, I get the following error message:

_/opt/monitor/speedtest.sh: 15: jq: not found
/opt/monitor/speedtest.sh: 16: jq: not found
{"error": "unable to parse 'bandwidth,server=,public=46.5.26.191 down=,up= 1711033870': missing tag value"}

**Comment by doebi** [comment]
Thanks.

Ah okay, seems as if you're missing the command line tool `jq` depending on your system you can install it with 
```
apt get install jq
yum install jq
etc
```

Let me know if that works!

All the best.

**Comment by Gitarist2018** [comment]
That was a very quick reply - thank you! Got it working with some modifications. In case someone else could need it:

1. _git clone https://github.com/doebi/speedtest_
2. Edit _speedtest/app/Dockerfile_
3. Append "jq" and "cron" to "RUN apt-get update && apt-get install -y curl wget iputils-ping" 
   Result: _RUN apt-get update && apt-get install -y curl wget iputils-ping jq cron_
4. Modified "RUN echo "*/15 * * * * /opt/monitor/speedtest.sh" >> /etc/cron.d/speedtest" to
   Result:  RUN echo "*/5 * * * * root /bin/sh /opt/monitor/speedtest.sh" >> /etc/cron.d/speedtest
5. Edit _speedtest/app/scripts/ping.sh_
6. For some reason cron needs to be restartet, so under "DB_PASSWORD="${DB_PASSWORD:-password}") I added 
_/etc/init.d/cron stop_ 
_sleep 5_ 
_/etc/init.d cron start_ 
7. inserted my ping hosts under (for host in **a.a.a.a b.b.b.b c.c.c.c** ; do...)
8. _sudo docker-compose build_
9. _sudo docker-compose up -d_
10. Opended _http://hostname:3004_ in Browser
11. Login to Grafana: _admin/admin_

**Comment by doebi** [comment]
Glad to hear it's working now. I'll close this issue then, feel free to open a new one if you have any more issues or send a PR with your changes.
